apiVersion: v1
kind: ServiceAccount
metadata:
  name: hazelcast

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  verbs:
  - get
  - list

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hazelcast
subjects:
- kind: ServiceAccount
  name: hazelcast
roleRef:
  kind: ClusterRole
  name: hazelcast
  apiGroup: rbac.authorization.k8s.io
